name: deploy

on: [push, pull_request]

jobs:
  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Test using Node.js 16.14
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 16.14
  #     - run: npm install
  #     - run: npm test
  deploy:
    # needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: auth
        id: auth
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
          
      - name: Prepare environment variables
        run: yarn app-engine:replace-env-vars
        env:
          DB_URL: ${{ secrets.DB_URL }}

      - name: Deploy to App Engine
        id: deploy
        uses: google-github-actions/deploy-appengine@v0
